import { StyleSheet, Platform } from "react-native";
import colors from "../../assets/colors/colors";
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from "react-native-responsive-screen";
const TaskStyle = StyleSheet.create({
  view: {
    backgroundColor: colors.white,
    borderRadius: 30,
    padding: 15,
    marginTop: 6,
  },
  top: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  text: {
    justifyContent: "center",
  },
  time: {
    fontSize: 14,
    fontFamily: "FredokaRegular",
    color: colors.black,
    marginBottom: 5,
  },
  title: {
    fontSize: 20,
    fontFamily: "FredokaRegular",
    color: colors.black,
    marginBottom: 5,
  },
  description: {
    fontSize: 16,
    fontFamily: "FredokaRegular",
    color: colors.black,
  },
  icon: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: 60,
    height: 60,
    left: -7,
    top: -10,
    alignItems: "center",
    borderRadius: 50,
  },
  icon3: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: 60,
    height: 60,
    left: -35,
    top: -10,
    alignItems: "center",
    borderRadius: 50,
  },
  iconS: {
    flexDirection: "row",
    justifyContent: "space-between",
    top: -10,
    alignItems: "center",
    borderRadius: 50,
  },
  avatarContainer: {
    width: 40,
    height: 40,
    borderWidth: 2,
    borderColor: colors.white,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarContainerS: {
    width: 40,
    height: 40,
    borderWidth: 3,
    borderColor: colors.white,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarContainer2: {
    width: 40,
    height: 40,
    borderWidth: 2,
    borderColor: colors.white,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: -12,
  },
  avatar: {
    width: 40,
    height: 40,
  },
  avatar2: {
    width: 40,
    height: 40,
  },
  avatar2p: {
    width: 40,
    height: 40,
    backgroundColor: colors.red,
    borderWidth: 2,
    borderColor: colors.white,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  avatar2pText: {
    fontSize: 14,
    fontFamily: "FredokaMedium",
    color: colors.white,
  },
  bottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 30,
  },
  bottomLeft: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  bottomRight: {
    justifyContent: "center",
  },
  txt: {
    fontSize: 18,
    fontFamily: "FredokaRegular",
    color: colors.black,
  },
  touch: {
    backgroundColor: colors.beige,
    borderRadius: 30,
    padding: 18,
  },
  iconx: {
    justifyContent: "center",
    backgroundColor: colors.black,
    width: 50,
    height: 50,
    alignItems: "center",
    borderRadius: 50,
  },
  modal: {
    justifyContent: "center",
    alignSelf: "center",
    bottom: Platform.OS === "ios" ? -20 : 0,
    position: "absolute",
    width: "100%",
  },
  modalContent: {
    backgroundColor: colors.white,
    height: hp("94%"),
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 15,
    width: "100%",
    alignSelf: "center",
  },
  modalBar: {
    borderBottomWidth: 6,
    borderBottomColor: colors.lightgray,
    width: 60,
    borderRadius: 30,
    alignSelf: "center",
    top: -5,
  },
  modalTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 5,
    paddingHorizontal: 5,
  },
  closeIcon: {
    backgroundColor: colors.beige,
    padding: 12,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  editIcon: {
    backgroundColor: colors.beige,
    padding: 12,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  modalMain: {
    //
  },
  modalTaskTxtBox: {
    justifyContent: "center",
    alignItems: "center",
  },
  modalTaskTimeText: {
    fontSize: 16,
    fontFamily: "FredokaMedium",
    color: colors.white,
    backgroundColor: colors.black,
    padding: 15,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  modalTaskTitleText: {
    fontSize: 26,
    fontFamily: "FredokaMedium",
    color: colors.black,
    paddingTop: 15,
    textAlign: "center",
  },
  modalTaskDescriptionText: {
    fontSize: 16,
    fontFamily: "FredokaRegular",
    color: colors.black,
    paddingTop: 5,
    textAlign: "center",
  },
  modalIcons: {
    alignSelf: "center",
    marginVertical: 20,
  },
  avatarM: {
    width: 60,
    height: 60,
  },
  avatarContainerSM: {
    width: 60,
    height: 60,
    borderWidth: 3,
    borderColor: colors.white,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  avatar2M: {
    width: 60,
    height: 60,
  },
  avatarContainerM: {
    width: 60,
    height: 60,
    borderWidth: 3,
    borderColor: colors.white,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: -20,
  },
  avatarContainer2M: {
    width: 60,
    height: 60,
    borderWidth: 3,
    borderColor: colors.white,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: -12,
  },
  iconM: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: 60,
    height: 60,
    alignItems: "center",
    borderRadius: 50,
    alignSelf: "center",
    // padding: 10,
    // right: 20,
  },
  icon3M: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: 60,
    height: 60,
    alignItems: "center",
    borderRadius: 50,
    marginLeft: -50,
  },
  avatar2pM: {
    width: 60,
    height: 60,
    backgroundColor: colors.red,
    borderWidth: 2,
    borderColor: colors.white,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  avatar2pTextM: {
    fontSize: 18,
    fontFamily: "FredokaMedium",
    color: colors.white,
  },
  modalTaskPlanText: {
    fontSize: 26,
    fontFamily: "FredokaMedium",
    color: colors.black,
    paddingVertical: 10,
    textAlign: "center",
  },
  modalPlanFirst: {
    marginVertical: 5,
    backgroundColor: colors.red,
    borderRadius: 30,
    padding: 20,
    flexDirection: "row",
    // alignItems: "center",
    justifyContent: "space-between",
  },
  modalPlan: {
    marginVertical: 5,
    backgroundColor: colors.lightgray,
    borderRadius: 30,
    padding: 20,
    flexDirection: "row",
    // alignItems: "center",
    justifyContent: "space-between",
  },
  modalPlanContent: {
    width: "74%",
  },
  modalPlanTime: {
    width: "24%",
  },
  modalPlanTxt: {
    textAlign: "left",
    fontSize: 20,
    fontFamily: "FredokaMedium",
    color: colors.white,
  },
  modalPlanTimeTxt: {
    textAlign: "right",
    fontSize: 16,
    fontFamily: "FredokaRegular",
    color: colors.white,
  },
  modalPlanTxtFirst: {
    textAlign: "left",
    fontSize: 20,
    fontFamily: "FredokaMedium",
    color: colors.black,
  },
  modalPlanTimeTxtFirst: {
    textAlign: "right",
    fontSize: 16,
    fontFamily: "FredokaRegular",
    color: colors.black,
  },
  modalTaskPlanText2: {
    fontSize: 20,
    fontFamily: "FredokaMedium",
    color: colors.lightgray,
    paddingTop: 80,
    textAlign: "center",
  },
  alertIcon: {
    color: colors.lightgray,
    alignSelf: "center",
    top: 15,
  },
});
export default TaskStyle;
